export {
    AddIcon,
    AltArrowDownIcon,
    AltArrowLeftIcon,
    AltArrowRightIcon,
    AltArrowUpIcon,
    ArrowDownIcon,
    ArrowLeftIcon,
    ArrowRightIcon,
    BoxIcon,
    Buildings2Icon,
    Buildings3Icon,
    BuildingsIcon,
    BusIcon,
    CalendarAddIcon,
    CalendarDateIcon,
    CalendarIcon,
    CalendarMarkIcon,
    CameraIcon,
    ChartIcon,
    ChatRoundDotsIcon,
    ChatRoundIcon,
    ChatRoundUnreadIcon,
    ChatSquareArrowIcon,
    ChatSquareIcon,
    CheckCircleIcon,
    CheckReadIcon,
    ChecklistIcon,
    ClipboardCheckIcon,
    ClipboardListIcon,
    ClockCircleIcon,
    CloseCircleIcon,
    CloseIcon,
    CloudUploadIcon,
    CodeScanIcon,
    CopyIcon,
    DangerCircleIcon,
    DangerTriangleIcon,
    DatabaseIcon,
    DisketteIcon,
    DislikeIcon,
    DocumentTextIcon,
    DownloadIcon,
    EyeClosedIcon,
    EyeIcon,
    FeedIcon,
    FileIcon,
    FilterIcon,
    FlameIcon,
    ForbiddenIcon,
    GalleryIcon,
    GraphUpIcon,
    HamburgerMenuIcon,
    HandHeartIcon,
    HandShakeIcon,
    HeartIcon,
    HeartPulseIcon,
    HistoryIcon,
    HouseIcon,
    InboxIcon,
    InfoCircleIcon,
    KeyIcon,
    LampIcon,
    LeafIcon,
    LetterIcon,
    LikeIcon,
    LinkIcon,
    ListIcon,
    LockKeyholeIcon,
    LogoutIcon,
    MagnifierIcon,
    MapIcon,
    MapPointIcon,
    MaximizeIcon,
    MedalRibbonIcon,
    MenuDotsCircleIcon,
    MenuDotsIcon,
    MinimizeIcon,
    MinusIcon,
    MonitorIcon,
    MoonIcon,
    PaletteIcon,
    PaperclipIcon,
    PauseIcon,
    Pen2Icon,
    PenIcon,
    PhoneIcon,
    PieChartIcon,
    PlayIcon,
    PlugCircleIcon,
    PowerIcon,
    PresentationGraphIcon,
    PulseIcon,
    QuestionCircleIcon,
    QuestionMarkIcon,
    RadarIcon,
    RecordIcon,
    RefreshCircleIcon,
    RefreshIcon,
    ReorderIcon,
    RestartIcon,
    SendSquareIcon,
    ServerIcon,
    SettingsIcon,
    ShieldCheckIcon,
    ShieldCrossIcon,
    ShieldIcon,
    ShieldUserIcon,
    ShieldWarningIcon,
    SortVerticalIcon,
    SquareAcademicCapIcon,
    SquareArrowRightUpIcon,
    SsdRoundIcon,
    StructureIcon,
    SuitcaseIcon,
    SunIcon,
    TagHorizontalIcon,
    TagIcon,
    ThreeSquaresIcon,
    ToolboxIcon,
    TransferHorizontalIcon,
    TrashBinTrashIcon,
    UnlinkIcon,
    UnreadIcon,
    UserCheckRoundedIcon,
    UserCircleIcon,
    UserRoundedIcon,
    UsersGroupRoundedIcon,
    VerifiedCheckIcon,
    WidgetIcon,
} from '@solar-icons/react/outline';

/**
 * Ponte entre os nomes de ícone usados no app e a biblioteca que os desenha.
 *
 * Os pontos de uso importam daqui, não da biblioteca: as avaliações de
 * Phosphor e Lucide foram trocas deste arquivo, sem encostar nos 76 arquivos
 * que desenham ícones. A escolha fechada é o `@solar-icons/react`.
 *
 * Os aliases no fim existem porque o CLI do shadcn gera componentes
 * importando ícones do lucide: ao trazer um componente novo, basta trocar
 * `lucide-react` por este módulo — os nomes que ele usa já estão aqui.
 */

export {
    HeartIcon as HeartBoldIcon,
    PlayIcon as PlayBoldIcon,
} from '@solar-icons/react/bold';

export {
    AltArrowDownIcon as ChevronDownIcon,
    AltArrowLeftIcon as ChevronLeftIcon,
    AltArrowRightIcon as ChevronRightIcon,
    AltArrowUpIcon as ChevronUpIcon,
    CheckCircleIcon as CheckIcon,
    MenuDotsIcon as MoreHorizontalIcon,
} from '@solar-icons/react/outline';
